2.0.0 master PR
BroadcomMFD/code4z pull request #57
Opened 2022-04-25 15:09 UTC by zeibura

Master PR for Code4z v2.0.0
Not ready yet - opening to check the diffs.

2022-04-27 12:50 UTC, zeibura commented
Ready for review now

2022-04-28 11:33 UTC, IgorCATech commented on README.md
> +Code4z is an all-in-one VS Code extension pack for mainframe users working with z/OS. Code4z provides language support for COBOL and High Level Assembler for z/OS and graphical visualization of COBOL
```suggestion
Code4z is an all-in-one VS Code extension pack for mainframe users working with z/OS. Code4z provides language support for COBOL and High Level Assembler for z/OS and graphical visualization of COBOL applications. The pack also includes data editing and file management tools, Explorer for Endevor, and extensions for interactive debugging, macro tracing, and abend analysis. Code4z is free to install and use.

```

2022-04-28 11:38 UTC, IgorCATech commented on README.md
> +The Code4z extension pack simplifies your common workflows and enables you to work with COBOL and HLASM code in the same way you work with other languages in Visual Studio Code. The pack provides a m
```suggestion
The Code4z extension pack simplifies your common workflows and enables you to work with COBOL and HLASM code in the same way you work with other languages in Visual Studio Code. The pack provides a modern mainframe programming experience and includes the following tools:

```

2022-04-28 11:39 UTC, IgorCATech commented on README.md
> +  - The COBOL Language Support and HLASM Language Support extensions provide syntax highlighting, syntax validation and content assist when editing COBOL and HLASM code. Code4z extensions utilize lan
```suggestion
  - The COBOL Language Support and HLASM Language Support extensions provide syntax highlighting, syntax validation, and content assistance when editing COBOL and HLASM code. Code4z extensions utilize language servers that are fully compatible with the [Language Server Protocol Specification](https://microsoft.github.io/language-server-protocol/specification). 

```

2022-04-28 11:48 UTC, IgorCATech commented on README.md
> +  - With Zowe Explorer you can allocate, copy, rename and edit mainframe data sets in VS Code and save them to the mainframe.
```suggestion
  - With Zowe Explorer you can allocate, copy, rename, and edit mainframe data sets in VS Code and save them to the mainframe. 

```

2022-04-28 11:49 UTC, IgorCATech commented on README.md
> +  - The Data Editor for Mainframe extension allows you to edit VSAM data sets, apply record layouts, and filter records using selection criteria.
```suggestion
  - The Data Editor for Mainframe extension enables you to edit VSAM data sets, apply record layouts, and filter records using selection criteria.

```

2022-04-28 11:49 UTC, IgorCATech commented on README.md
> +  - The Debugger for Mainframe extension lets you debug CICS and Batch applications written in COBOL.
```suggestion
  - The Debugger for Mainframe extension enables you to debug CICS and Batch applications that are written in COBOL. 

```

2022-04-28 11:49 UTC, IgorCATech commented on README.md
> +  - The HLASM Language Support extension lets you trace Assembler macros interactively.
```suggestion
  - The HLASM Language Support extension enables you to trace Assembler macros interactively.

```

2022-04-28 11:51 UTC, IgorCATech commented on README.md
> +  - Using the Explorer for Endevor extension you can retrieve, browse and search Endevor elements in your IDE.
```suggestion
  - With the help of the Explorer for Endevor extension you can retrieve, browse, and search Endevor elements in your IDE.

```

2022-04-28 11:51 UTC, IgorCATech commented on README.md
> +  - With Zowe Explorer you can issue TSO and MVS commands, and submit JCLs.
```suggestion
  - With Zowe Explorer you can issue TSO and MVS commands and submit JCLs.

```

2022-04-28 11:52 UTC, IgorCATech commented on README.md
> +* Use VS Code’s built-in Git interface to clone source code from Endevor using Endevor’s Bridge for Git.
```suggestion
* Use the VS Code built-in Git interface to clone source code from Endevor, using Endevor Bridge for Git.

```

2022-04-28 11:53 UTC, IgorCATech commented on README.md
> +* Edit COBOL code using COBOL Language Support, taking advantage of all the coding assistance provided by the extension.
```suggestion
* Edit COBOL code using COBOL Language Support to enjoy all the coding assistance that is provided by the extension.

```

2022-04-28 11:54 UTC, IgorCATech commented on README.md
> +* Locate all copybooks in the Git folder structure, and if needed, download other copybooks used in the source code from the mainframe.
```suggestion
* Locate all copybooks in the Git folder structure and, if needed, download other copybooks that are used in the source code from the mainframe.

```

2022-04-28 11:55 UTC, IgorCATech commented on README.md
> +* Use VS Code’s built-in Git interface to push, pull and merge changes.
```suggestion
* Use the VS Code built-in Git interface to push, pull, and merge changes.

```

2022-04-28 11:55 UTC, IgorCATech commented on README.md
> +* Search and browse additional code elements in the entire map of Endevor using the Explorer for Endevor extension. The COBOL Language Support extension provides syntax awareness for COBOL elements.
```suggestion
* Search and browse additional code elements in the entire map of Endevor, using the Explorer for Endevor extension. The COBOL Language Support extension provides syntax awareness for COBOL elements.

```

2022-04-28 11:56 UTC, IgorCATech commented on README.md
> +* Download code elements, including their dependencies, into the current workspace using the Explorer for Endevor extension, and synchronize them with the Git project if code modifications are needed
```suggestion
* Download code elements, including their dependencies, into the current workspace, using Explorer for Endevor, and synchronize them with the Git project if code modifications are needed.

```

2022-04-28 12:09 UTC, IgorCATech commented on README.md
> +COBOL Language Support enhances the COBOL programming experience on your IDE. The extension leverages the language server protocol to provide autocomplete, syntax highlighting and coloring, and diagn
```suggestion
COBOL Language Support enhances the COBOL programming experience on your IDE. The extension leverages the language server protocol to provide autocomplete, syntax highlighting and coloring, and diagnostic features for COBOL code and copybooks. The COBOL Language Support extension can also connect to a mainframe using the Zowe Explorer extension to automatically retrieve copybooks that are used in your programs and store them in your workspace.

```

2022-04-28 12:12 UTC, IgorCATech commented on README.md
> +COBOL Control Flow provides graphical visualization of program flow for programs written in COBOL. The extension is designed to help COBOL developers to quickly comprehend and debug COBOL programs wi
```suggestion
COBOL Control Flow provides graphical visualization of program flow for programs that are written in COBOL. The extension is designed to help COBOL developers to quickly comprehend and debug COBOL programs that they might not be familiar with.

```

2022-04-28 12:15 UTC, IgorCATech commented on README.md
> +HLASM Language Support is an extension that supports the High Level Assembler language. It provides code completion, highlighting and navigation features, shows mistakes in the source, and lets you t
```suggestion
HLASM Language Support is an extension that supports the High Level Assembler language. The extension provides code completion, highlighting and navigation features, shows mistakes in the source, and enables you to check how the conditional assembly is evaluated with a modern debugging experience.

```

2022-04-28 12:17 UTC, IgorCATech commented on README.md
> +The Data Editor for Mainframe extension for VS Code adds a modern user interface to [File Master Plus for MVS](https://www.broadcom.com/products/mainframe/testing-and-quality/file-master-plus). Data
```suggestion
The Data Editor for Mainframe extension for VS Code adds a modern user interface to [File Master Plus for MVS](https://www.broadcom.com/products/mainframe/testing-and-quality/file-master-plus). Data Editor for Mainframe enables you to view and edit mainframe data sets, including VSAM data sets, in your IDE.

```

2022-04-28 12:17 UTC, IgorCATech commented on README.md
> +- Browse and edit VSAM data sets, sequential data sets and PDS members.
```suggestion
- Browse and edit VSAM data sets, sequential data sets, and PDS members.

```

2022-04-28 12:18 UTC, IgorCATech commented on README.md
> +Abend Analyzer for Mainframe provides an interface to [SymDump® CICS](https://www.broadcom.com/products/mainframe/testing-and-quality/symdump-cics) and [SymDump® Batch](https://www.broadcom.com/produ
```suggestion
Abend Analyzer for Mainframe provides an interface to [SymDump® CICS](https://www.broadcom.com/products/mainframe/testing-and-quality/symdump-cics) and [SymDump® Batch](https://www.broadcom.com/products/mainframe/testing-and-quality/symdump-batch). The extension enables you to browse, manage, and view formatted abend reports and symbolic data in a modern IDE environment.

```

2022-04-28 12:19 UTC, IgorCATech requested changes
I've left a few suggestions

2022-04-28 13:23 UTC, IgorCATech commented on README.md
> +* Use the VS Code built-in Git interface to clone source code from Endevor, using Endevor Bridge for Git.
I don't like the double `use` here... but I don't have a better suggestion :)

2022-04-28 13:30 UTC, IgorCATech approved these changes
Thank you for addressing the comments. LGTM!

2022-04-28 15:02 UTC, merged